spring.application.name=restaurant-tree-app
server.port=8081

app.storage=mongo

spring.data.mongodb.uri=mongodb://localhost:27017/restaurant_tree_system
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
